import { renderToTemplate } from "@pdfme/jsx";
import { generate } from "@pdfme/generator";
import { text, multiVariableText } from "@pdfme/schemas";
import { writeFileSync } from "node:fs";

const data = {
  personal: { firstName: "Jean", lastName: "Dupont", email: "jean@x.com", phone: "+33 6 00", address: "12 rue X", city: "Paris", postalCode: "75002", country: "France", linkedin: "linkedin.com/in/jd", website: "", summary: "Résumé de test." },
  experiences: [{ id: "e1", position: "Dev", company: "Corp", location: "Paris", startDate: "2020", endDate: "2022", current: false, description: "Desc." }],
  education: [{ id: "ed1", degree: "Master", institution: "Uni", location: "Paris", startDate: "2018", endDate: "2020", description: "" }],
  skills: ["TS", "React"],
  languages: [{ id: "l1", name: "Français", level: "Natif" }],
};

console.log("importing academic template...");
const { AcademicTemplate } = await import("./components/cv/templates/academic.tsx");
console.log("calling component...");
const element = AcademicTemplate({ data });
console.log("element kind:", element.kind);
console.log("calling renderToTemplate...");
const result = await renderToTemplate(element);
console.log("OK template size:", JSON.stringify(result.template).length);
console.log("calling generate()...");
const pdfBytes = await generate({ template: result.template, inputs: result.inputs, plugins: { Text: text, MultiVariableText: multiVariableText } });
console.log("generated bytes:", pdfBytes.length);
writeFileSync("./_tmp_test.pdf", pdfBytes);
console.log("wrote _tmp_test.pdf");
